# Generated by Django 5.1.7 on 2025-03-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='preprocessor_file',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
